# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/my-story"

# 网页的标题
title: "A Mother's Story"
username: "A Mother"
# 网站副标题
description: "Not to sadden you but..."

aboutme: "Hoping for a gender-equal future"

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
